parameters:
#    php_women_admin.example.class: PHPWomen\AdminBundle\Example

services:
#    php_women_admin.example:
#        class: %php_women_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
