---
- name: nginxphp | Install Nginx
  apt: pkg=nginx state=latest

- name: nginxphp | Install php5-fpm
  apt: pkg=php5-fpm state=latest

- name: nginxphp | Check default php5-fpm user
  shell: grep -c 'www-data' /etc/php5/fpm/pool.d/www.conf
  register: phpuser_check
  ignore_errors: yes

- name: nginxphp | Change default php5-fpm user
  shell: sed -i 's/www-data/vagrant/' /etc/php5/fpm/pool.d/www.conf
  when: phpuser_check > 0
  notify: restart php5-fpm

- name: nginxphp | Change default nginx site
  template: src=files/nginx/default.tpl dest=/etc/nginx/sites-available/default
  notify: restart nginx

- name: nginxphp | Install PHP Modules
  apt: pkg={{ item }} state=latest
  with_items: php_packages

- name: nginxphp | Install Composer
  shell: curl -sS https://getcomposer.org/installer | php && mv composer.phar /usr/local/bin/composer creates=/usr/local/bin/composer