parameters:
#    php_women_user.example.class: PHPWomen\UserBundle\Example

services:
#    php_women_user.example:
#        class: %php_women_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
